make-midp-spacerun
make-midp-pubman
make-midp-munchies
make-midp-cavernsoffire
make-midp-dungeonsofhack
make-midp-matrixminer
make-midp-ogrotron

doshrinkjar CavernsOfFireMidlet manifests\manifest_midp_cavernsoffire
doshrinkjar DungeonsOfHackMidlet manifests\manifest_midp_dungeonsofhack
doshrinkjar MatrixMinerMidlet manifests\manifest_midp_matrixminer
doshrinkjar MunchiesMidlet manifests\manifest_midp_munchies
doshrinkjar OgrotronMidlet  manifests\manifest_midp_ogrotron
doshrinkjar PubManMidlet manifests\manifest_midp_pubman
doshrinkjar SpaceRunMidlet manifests\manifest_midp_spacerun

